### PR TITLE
Digistuff piston mvps

### PR DESCRIPTION
**Pull request by S-S-X**
https://github.com/pandorabox-io/pandorabox.io/issues/616

### CODE REVIEW

**Comment by S-S-X** [comment]
@OgelGames have extra time to check? Wrote this on web browser so not much testing done.. but I think it should do the trick.

But only for newly placed pistons.

**Comment by OgelGames** [comment]
I can't test it right now either, but the code looks correct 👍 

Also, yet another reason to fork digistuff...

**Comment by OgelGames** [comment]
Doesn't work, the owner also needs to be passed to the function: https://github.com/minetest-mods/mesecons/blob/583d2c144165545f10a04075f1f215d829da1ab2/mesecons_pistons/init.lua#L86

I'm all for forking digistuff, so we can fix all the little bugs it has, I'm just not sure how to setup the automatic pulling from upstream like was done for technic...

**Comment by S-S-X** [comment]
> Doesn't work, the owner also needs to be passed to the function: https://github.com/minetest-mods/mesecons/blob/583d2c144165545f10a04075f1f215d829da1ab2/mesecons_pistons/init.lua#L86
> 
> I'm all for forking digistuff, so we can fix all the little bugs it has, I'm just not sure how to setup the automatic pulling from upstream like was done for technic...

Yeah, that really sounds like best approach... so far too many hacks too often and too hard to communicate problems to upstream.
I'll see if I can do something about it.

**Comment by OgelGames** [comment]
~~I think I figured it out: https://github.com/mt-mods/digistuff~~

**Comment by S-S-X** [comment]
> I think I figured it out: https://github.com/mt-mods/digistuff

Commented on Discord right after I got error that repo is already created and then saw it was actually fork of mirror repo.
>  SX: @OgelGames (AceRichman) please do not fork from minetest-mirrors
> [08.16] SX: forking trashes a lot of functionality, noticed just because I was going to add repo. better to fix it now
> [08.17] SX: better to create full feature repo and pull directly from upstream and leave github mirror repo completely out of it

Pullbot cannot do this but there seems to be alternatives that should be able to do it, never used any of those so not yet sure what it would take to keep that mitm away.

**Comment by OgelGames** [comment]
I deleted it, I should have just let you do it, sorry... Also I should have discord open :P

**Comment by OgelGames** [comment]
Closing this, because it will be fixed in the fork. (https://github.com/mt-mods/digistuff)

**Comment by cheapie** [comment]
This has been fixed upstream in commit ad062495d8188539bb6ac7f558e9ade50076ecd5. Existing pistons are (currently) exempt from the change as there's no good way to determine who should own them, but new pistons now keep track of their owner and respect protection.

**Pull request closed without merging**
