### PR TITLE
Add sand/sandstone dyeing recipes

### PR DESCRIPTION
**Pull request by OgelGames**
Added crafting recipes for dyeing sand and sandstone, allowing for conversion between silver, desert, and regular sand/sandstone.

Fixes issue: https://github.com/pandorabox-io/pandorabox.io/issues/259

### CODE REVIEW

**Comment by thomasrudin** [comment]
thx, where can i direct the bug-bounty to?  :smile:

**Comment by OgelGames** [comment]
Oh, AceRichman is my in-game username, if that's what you mean...

**Comment by thomasrudin** [comment]
Yes, and i'm tracking the contributors now, if thats alright:
https://github.com/pandorabox-io/pandorabox.io/commit/b46d8ad3b62c10ce6c663f70c040ec7e84b24bab

**Comment by OgelGames** [comment]
Sure, that's great, thanks. 😄

**Pull request merged**
