### PR TITLE
Also allow spacecannon use deep underground.

### PR DESCRIPTION
**Pull request by dennisjenkins75**
I would like to experiment using a spacecannon in a creative mining endeavour please :)

### CODE REVIEW

**Comment by FeXoR-o-Illuria** [comment]
Underground, especially deep underground between -4K and -32K, is where many players have their safe haven.
I do not think that is the right place to allow canons.

Space canons can already be fired on moon and above (y > 1000) so basically half the map.
I also received a PM from a "concerned citizen" regarding not being so found and moving his base into space ... oh, right: Canons can be used there already :p

Sure, the map is big and collisions of interest - "Hey, cool, I can vaporize the earth. Yippie! Jump around. Jump! Jump! Jump!" and "Hm, if I place this flowerpot over their the chi would fly a lot better in this cosy ... what was that? An explosion? Here?" may actually stay rare.

**Comment by BuckarooBanzay** [comment]
There have been some concerns about the usage of the cannons everywhere, my proposal:
* Y-Limit: above 1000 and below -1000
* XP-Limit (priv-based so exceptions could be granted) to 100k

Protections are checked everywhere except the warzone of course

@S-S-X (#36)

**Comment by FeXoR-o-Illuria** [comment]
Ruggila's tests seem to indicate that at least protection blocks protect against canon projectiles well.
Also canons can't be used in protections my others.
Area protections have not been checked yet.
Regarding the depth: I think they should not be usable to fire at any player descending to the max ore density depth so I would say -10K would be better.

Canons can't be used well to mine for most blocks get destroyed
(I like that they are bad at mining. I don't like that they destroy blocks ;)

l I'm not so found of any nodebreaking projectiles. I don't like Dungeon Masters or Xenomorphs, despise those exploding pumpkins on other servers as well as dynamite and alike nuclear arrows.
And I think a peaceful region has it's value all on it's own ... just that you know my point of view ;)

**Comment by BuckarooBanzay** [comment]
a priv was added in 863fd6e987533fb54d5fc690331acc4eb7f7efc9 for unrestricted spacecannon use (yes, protected stuff will not be harmed) this is not needed anymore i think, otherwise reopen...

**Pull request closed without merging**
