### PR TITLE
Announce player revival

### PR DESCRIPTION
**Pull request by SwissalpS**
revert some of the eliminations in https://github.com/pandorabox-io/pandorabox_custom/commit/e99f8e581eff24b917bca4a97bd04e1588015b08

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
looks good, does this work with the `beerchat` mod? (haven't checked the code there yet, sorry)

**Comment by SwissalpS** [comment]
IDK, I abborted testing locally as the message didn't come through even without [beerchat] or these changes active.

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by SwissalpS** [comment]
How ironic, I was for the removal back then and now I'm the one adding it back in :D

**Comment by SwissalpS** [comment]
Seems to work for in-game chat but on IRC the messages persist.
Also the messages issued with the chatcommands work in-game but not on IRC.
Is it beerchat or is it another bridge that posts on IRC?

**Comment by SwissalpS** [comment]
found it:
https://github.com/mt-mods/beerchat/blob/4b146ccc02eb3d7ea8a100722163d45312b14dbd/web/tx.lua#L42-L63

I see two ways of going about this:

1. expose the functions in [beerchat] so we can override them in [pandorabox_custom]
2. add this as a feature to [beerchat]

Any other ideas? And which path is cleanest?

Edit: if 2. then probably best to change the name of the priv to `no_announce_join_leave`
(or similar) as there is another announce feature in [beerchat].

**Comment by SwissalpS** [comment]
3. override `beerchat.on_channel_message` <-- this seems worst choice though, inspecting every message just in case it is a join/leave message.

**Comment by SwissalpS** [comment]
Well, 3. seemed to be the easiest and fastest way to get this feature going, so #86

**Pull request merged**
